### ISSUE TITLE
图片表格标题字体调整，图表索引处取消分章节

### ISSUE THREAD

**Issue by JXJiangXu** [hnuthesis/hnuthesis#20]
1. 佬，当我编译时，图表标题会显示这个警告LaTeX Font: Font shape `TU/SimSun(1)/b/n' undefined ，(Font)	using `TU/SimSun(1)/m/n' instead.LaTeX，然后编译出的图表标题还是宋体字，能否换成黑体？
2. 插图索引和表格索引的生成，不同章节的会多一行空格，能否取消?

**Comment by totalo** [comment]
实用最新版本即可
