### ISSUE TITLE
黑体在正文中无法通过\textbf指令加粗

### ISSUE THREAD

**Issue by bulkee** [hnuthesis/hnuthesis#21]
如题，建议参考上交latex格式进行修改。参考信科院以往毕业论文，建议倍数设定为4。

ref：https://github.com/sjtug/SJTUThesis/issues/566

**Comment by totalo** [comment]
可以参考 readme ：https://github.com/hnuthesis/hnuthesis/blob/dad750a02514dae69e4fb89ad3cc131097d78987/README.md?plain=1#L74
