### ISSUE TITLE
仓库维护相关问题

### ISSUE THREAD

**Issue by totalo** [hnuthesis/hnuthesis#23]
学长，您好，这个仓库和模板很有用，如果您没时间的话，可以开放维护的权限嘛？我这边新建了一个仓库，修复了一些问题，如果可以开放维护，希望把修改合并到这个仓库，然后后续持续更新。后面有学弟学妹发现问题也可以提交 pr 一起修复，https://github.com/totalo/hnuthesis-x

**Comment by yusanshi** [comment]
赞！
已转移至 https://github.com/hnuthesis/hnuthesis，并邀请你加入hnuthesis这个组织～  做你想做的吧我实在没精力和能力了😭

**Comment by totalo** [comment]
> 赞！ 已转移至 [https://github.com/hnuthesis/hnuthesis，并邀请你加入hnuthesis这个组织～](https://github.com/hnuthesis/hnuthesis%EF%BC%8C%E5%B9%B6%E9%82%80%E8%AF%B7%E4%BD%A0%E5%8A%A0%E5%85%A5hnuthesis%E8%BF%99%E4%B8%AA%E7%BB%84%E7%BB%87%EF%BD%9E) 做你想做的吧我实在没精力和能力了😭

好，谢谢学长，冲鸭！
